- name: Install hardened kernel/headers
  become: true
  command: pacman -Syyu --noconfirm linux-hardened linux-hardened-headers
  register: hardened
- name: Remove original kernel
  become: true
  command: pacman -Rs --noconfirm linux
  when: hardened.changed
  register: removal
- name: Update GRUB
  become: true
  command: grub-mkconfig -o /boot/grub/grub.cfg
  when: removal.changed
  register: grub

